Adding bootstrap tuturial - first version
jorgerdc/tutoriales pull request #11
Opened 2019-04-13 02:37 UTC by jorgerdc

Primer PR del tutorial de bootstrap.

2019-04-15 18:34 UTC, alexJava2015 requested changes

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Representa uno de los frameworks front-end más populares empleados para construir sitios responsivos, con una gran variedad de elementos gráficos, templates entre otros.
Cambiar a español la palabra "template" según lo acordado.

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* El siguiente código muestra la plantilla básica para iniciar a trabajar con Bootstrap.  Importente:
Al parecer hay una falata de ortografía en la palabra "Importente", favor de corregirla.

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +	* Algunos componentes hacen uso de JQuery, Popper.js así como algunos plugins JS.
Sería bueno poner una breve descripción o liga para la definición de Popper.js, ya que para un recurso que no tiene contexto web podría causar ruido.

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +	* Uso de Reboot para proporcionar un *render* homogéneo entre navegadores y dispositivos móviles.
Como propuesta se puede poner una liga con la definición de "Reboot" yo al menos me quede de a 6 hasta que no leí la definición:
https://getbootstrap.com/docs/4.0/content/reboot/

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Bootstrap puede incorporarse haciendo uso de  BootstrapCDN  (Content Delivery Network).  Esta técnica se empleó en el ejemplo anterior.   Se trata de un URL público en donde se  encuentra la bootst
Sería bueno mencionar lo que me comentaste el otra vez respecto a comentar que es mejor usar una instalación local.

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Las variables  Saas tienen definen valores por default.  Estos valores pueden ser sobrescritos empleando scripts saas  (archivos con extensión saas: `custom.scss`). El archivo personalizado realiza
Esta mal redactado el siguiente texto " . . . tienen definen . . ." favor de corregirlo

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +```scss
Este ejemplo no queda claro a que refiere, falta especificar que se esta representando.

2019-04-15 18:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Este tipo de definiciones se pueden sobrescribir empleando un archivo `saas`personalizado.
Se puede agregar un ejemplo de como se hace la sobre escritura.

2019-06-15 18:06 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* Representa uno de los frameworks front-end más populares empleados para construir sitios responsivos, con una gran variedad de elementos gráficos, templates entre otros.
resuelto.

2019-06-15 18:07 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* El siguiente código muestra la plantilla básica para iniciar a trabajar con Bootstrap.  Importente:
corregido

2019-06-15 18:09 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +	* Algunos componentes hacen uso de JQuery, Popper.js así como algunos plugins JS.
Ok, agregué ligas

2019-06-15 18:11 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +	* Uso de Reboot para proporcionar un *render* homogéneo entre navegadores y dispositivos móviles.
Listo.

2019-06-15 18:14 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* Bootstrap puede incorporarse haciendo uso de  BootstrapCDN  (Content Delivery Network).  Esta técnica se empleó en el ejemplo anterior.   Se trata de un URL público en donde se  encuentra la bootst
Ya no me acuerdo. Podrías sugerir lo que debería de agregarse aquí ?
Evita poner comentarios como "Lo que platicamos la otra vez",  "Según lo acordado en una reunión".  Este tipo de frases hacen referencia a acuerdos  hechos verbalmente, pero no se quedan asentados o documentados en ningún lado. Entonces, sería bueno que aquí documentes o describas el acuerdo..

2019-06-15 18:15 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* Las variables  Saas tienen definen valores por default.  Estos valores pueden ser sobrescritos empleando scripts saas  (archivos con extensión saas: `custom.scss`). El archivo personalizado realiza
Listo.

2019-06-15 18:15 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +```scss
Es solo una introducción. Agregué un enunciado donde se indica que se hablará de esto más adelante.

2019-06-15 18:18 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* Este tipo de definiciones se pueden sobrescribir empleando un archivo `saas`personalizado.
De forma similar, este capítulo es de introducción.  Agregaré una nota para indicar que se hablará a detalle más adelante.

2019-06-15 23:33 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Representa uno de los frameworks front-end más populares empleados para construir sitios responsivos, con una gran variedad de elementos gráficos, templates entre otros.
Cerrado.

2019-06-15 23:34 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* El siguiente código muestra la plantilla básica para iniciar a trabajar con Bootstrap.  Importente:
Validado.

2019-06-16 00:11 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Las variables  Saas tienen definen valores por default.  Estos valores pueden ser sobrescritos empleando scripts saas  (archivos con extensión saas: `custom.scss`). El archivo personalizado realiza
Validado!

2019-06-16 00:12 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Este tipo de definiciones se pueden sobrescribir empleando un archivo `saas`personalizado.
De acuerdo, con el cambio.

2019-06-16 00:13 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +```scss
Validado.

2019-06-16 00:38 UTC, alexJava2015 commented on bootstrap/docs/modulo01.md
> +* Bootstrap puede incorporarse haciendo uso de  BootstrapCDN  (Content Delivery Network).  Esta técnica se empleó en el ejemplo anterior.   Se trata de un URL público en donde se  encuentra la bootst
De acuerdo con el comentario, de echo también se me estaba olvidando, lo que me refiero es que en vez de usar CDN, de lo que recuerdo no es tan bueno porque puden varias las versiones e incluso no ser compatibles, entonces es mejor mantener una instalación en nuestra maquina con la versión deseada para eviar problemas con las versiones de la nube por inconpatibilidad.

2019-07-21 00:17 UTC, merged