Initial commit for  ReactJS tutorial -module 01
jorgerdc/tutoriales pull request #12
Opened 2019-04-28 06:00 UTC by jorgerdc

Please @alexJava2015  Review  this initial commit .

2019-08-10 22:52 UTC, alexJava2015 requested changes

2019-08-10 22:52 UTC, alexJava2015 commented on reactjs/docs/modulo01.md
> +}
En este código se observan elementos en una lista con tags html "<li>" sin embargo por lo que veo son "hard code", me crea confusión puesto que por lo que entiendo el ciclo "for" debe iterar el contenido de props y pintar los valores correspondientes, sin embargo en la sección de los "<li>" estan "hard code".

2019-08-10 22:52 UTC, alexJava2015 commented on reactjs/docs/modulo01.md
> +```
Creo debería poner una descripción o liga donde se especifique cada uno de los parametros que se estan declarando.

2019-08-15 21:04 UTC, jorgerdc reviewed
Listo, comentarios revisados.
En esta ocasión no modifiqué código. 
De favor, revisa mis comentarios, tengo dudas en cuanto a lo que se pide.

2019-08-15 21:04 UTC, jorgerdc commented on reactjs/docs/modulo01.md
> +}
Realmente no entiendo tu comentario.
En ReactJS puedes poner el código HTML combinado con Javascript. 
En este caso el código HTML está como parámetro de la función return.
No se si esto aclara la duda,  o ¿qué debo modificar? tu comentario no me dice qué modificar.

2019-08-15 21:04 UTC, jorgerdc commented on reactjs/docs/modulo01.md
> +```
Podrías listar los parámetros a los que te refieres ? yo solo veo un parámetro (user). Pero si observas, no creo que necesite descripción puesto que justo abajo se define quien es "user", un
simple objeto javascript con  properties, como si fuera un POJO.
myElement es el otro parámetro, pero ese se explica en el documento. Entonces, no se a qué parámetros te refieres...

2019-08-15 22:39 UTC, alexJava2015 requested changes

2019-08-15 22:39 UTC, alexJava2015 commented on reactjs/docs/modulo01.md
> +}
A lo que me refiero es que en la lista <li> pones: Boostrap, Angular, etc. pero es confuso, no se debería poner una variable, algo como  <li>{this.props.name.xx}</li>.

2019-08-15 22:39 UTC, alexJava2015 commented on reactjs/docs/modulo01.md
> +```
Omite este comentario, la verdad no veo porque lo puse, como dices esta bien explicado el código.

2019-08-16 20:37 UTC, jorgerdc reviewed
Comentarios a la segunda revisión.
No se aplica cambios al código.
De favor, revisar.

2019-08-16 20:37 UTC, jorgerdc commented on reactjs/docs/modulo01.md
> +}
Nooo.   
Este ejemplo solo define un parámetro llamado "name" , esto lo puedes ver en la línea 29: 
 `<CourseList name="myCourses">`   La idea de este parámetro es asignarle un  nombre a la lista de cursos.
En ReactJS, tu puedes emplear este parámetro para incluirlo en html que se va a producir.
En este ejemplo, en la línea 16 se usa el parámetro para producir esta cadena: <h1>CourseList for myCourses </h1>
Si tu idea es que la lista de cursos se resolviera de forma dinámica, ahí tendrías que pasarle a ReactJS una
lista de parámetros para ser sustituidos en los elementos `<li>`  

Se entiende  ? Esto lo explico en las líneas 31 a la 33

2019-08-16 20:37 UTC, jorgerdc commented on reactjs/docs/modulo01.md
> +```
ok, resuelvo conversación.

2019-08-20 01:05 UTC, alexJava2015 requested changes

2019-08-20 01:05 UTC, alexJava2015 commented on reactjs/docs/modulo01.md
> +}
Si entiendo la idea, lo que veia raro el poque se ponia de forma directa en los <li> los nombres como boostrap, etc, pero solo es para ejemplificar y sí los queremos de forma dinamica los tenemos quedar el tratamiento adecuado como se explica en las líneas 31 a 33.

2020-03-21 18:38 UTC, alexJava2015 approved these changes

2020-03-21 18:45 UTC, merged