Adding module 2, doc and examples
jorgerdc/tutoriales pull request #13
Opened 2019-05-05 23:54 UTC by jorgerdc

Please @alexJava2015  Review this new PR

2019-08-09 17:21 UTC, alexJava2015 requested changes

2019-08-09 17:21 UTC, alexJava2015 commented on reactjs/docs/modulo02.md
> +##### Ejemplo:
Anteriormente comentaste sobre el elemento raíz "root" sin embargo en el ejemplo no veo este, supongo que es un default y no nesecita especificarse. ¿ Lo puedes confirmar porfa ?

2019-08-09 17:21 UTC, alexJava2015 commented on reactjs/ejemplos/modulo02/componentes.html
> +<!DOCTYPE html>
Este código por lo que veo es similar a la sección de arriba donde se describe el uso de: render, app, elementos, etc. creo se duplico, o cual es la razón de que este dos veces, creo se presta para confusión.

2019-08-15 20:26 UTC, jorgerdc reviewed
Se han contestado los comentarios.
El cambio realizado se subirá en el siguiente commit.

2019-08-15 20:26 UTC, jorgerdc commented on reactjs/docs/modulo02.md
> +##### Ejemplo:
Ok, se agrega una viñeta para complementar y se entienda mejor.

2019-08-15 20:26 UTC, jorgerdc commented on reactjs/ejemplos/modulo02/componentes.html
> +<!DOCTYPE html>
En realidad No.  Si observas, este archivo se llama componentes.html.  El archivo contiene el código completo del ejemplo. Dicho archivo se puede abrir en el browser para probar la funcionalidad.
Efectivamente, parte del código de este ejemplo fue tomado para incluirlo en la documentación como ejemplo. Me explico?
Es como si tuvieras una clase Java, y tomas algunas líneas y las pegas en el tutorial para explicar un concepto.

2019-08-20 01:08 UTC, alexJava2015 commented on reactjs/ejemplos/modulo02/componentes.html
> +<!DOCTYPE html>
De acuerdo, de hecho me di cuenta de esto y sí es nesario, lo lo hice en el de log4j2.

2019-08-20 01:08 UTC, alexJava2015 commented on reactjs/docs/modulo02.md
> +##### Ejemplo:
Perfecto, se cierra el caso.

2020-03-21 17:45 UTC, alexJava2015 approved these changes

2020-03-21 18:47 UTC, merged