Add file documentation and project source of log4j2.
jorgerdc/tutoriales pull request #14
Opened 2019-06-02 00:34 UTC by alexJava2015

File contains changes of new version and environment configuration. The project have basic structure to use file properties and execute classic HelloWorld example.

2019-06-15 20:24 UTC, jorgerdc requested changes
Listo. Please revisar comentarios.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* No permite multiples implementaciones.
¿ No permite?  O tal vez sale sobrando la palabra "no" ?

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +### Ecosistema
Agregar numeración.  Apartir de este punto perdiste la numeración de los subtemas.  El título de "Configuración" sería el punto  1.2 o sería parte del punto 1.1? algo así como 1.1.1 ??
Evita poner dobles títulos. Es decir,  ¿ por qué pusiste "Ecosistema" justo después del titulo "Configuración" ? ¿ se trata de un subtema ?
Tal vez quisiste decir:
### 1.2 Configuración de Log4J
#### 1.2.1 Ecosostema

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Para esta versión se tienen diversas `appenders` para poder configurar la bitácora de una manera más clara y consciza, a continucación se listan algunos:
El primer párrafo no tiene relación alguna con el segundo. En el primero hablas de las herramientas para la administración de proyectos, y en el segundo hablas del concepto de  *appender*  Entonces como que saca un poco de onda, no les veo la relación.
Por otro lado, en el segundo párrafo se explican ejemplos de appenders, pero creo que vale la pena escribir una breve descripción del concepto de *Appender*  Por lo que veo creo que la idea de un appender ha cambiado con respecto a la versión 1.  Entonces si es importante repasar su definición.
En la versión 1 no existía la idea de que un appender se puede extender al uso de otros frameworks como son MongoDB, etc, etc.. Entonces es importante explicar esto.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* En la siguiente liga se encuentrar la configuración tradicional y appenders mencionados en el punto anterior: https://logging.apache.org/log4j/2.x/maven-artifacts.html
typo:   encuentrar  -> encuentran

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +### Archivo de configuración o implementación
agregar numeración

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Existen 4 diversos tipo de configuración o implementación, tales como:
Sugiero el siguiente texto.
Existen diversos formatos para realizar la configuración de Log4J:

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +	* Para configurar cada una de las implementaciones visitar la liga correspondiente.
Revisar la indentación.  El asterisco está demasiado a la derecha. Lo mismo para los nùmeros 1,2,3,4.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Log4J2 cuenta con una configuración por default si no encuentra archivo a cargar.
Sugiero: 
Log4J2 cuenta con una configuración por default que es aplicada en caso de no encontrar archivos de configuración.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* `ConfigurationFactory` contiene lógica para encontrar la implementación a cargar, el orden de busqueda es el siguiente :
Creo que la palabra "implementación" no es la correcta.
Sugiero  reemplazar los 2 renglones anteriores por lo siguiente:
Log4J2 define la clase `ConfigurationFactory` encargada de detectar la presencia de archivos de configuración con base a las siguientes reglas:

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +	1. Primero buscará el archivo especificado en la propiedad: "log4j.configurationFile".
Mejorar la descripción.
1. Se intenta ubicar el archivo especificado por una JVM system property:  `log4j.configurationFile`

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +	2. Si no existe el archivo `log4j.configurationFile` la clase `ConfigurationFactory` buscará `log4j2-test.properties`.
Sugiero: En caso de no existir el archivo especificado en el punto anterior, la clase ....
¿ en donde busca ?,  Misma pregunta para los demás puntos.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +### Configurando log42 con archivo de propiedades
Sugiero:
##### Ejemplo: Configurando  Log4J2 a través de un archivo properties.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Agregar archivo log42.properties en la ruta: `/src/main/resources`
Ojo:  es log42.properties  o  es log4j2.properties ?

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +Datos de archivo de propiedades
Esta linea creo que ya sale sobrando. Con la anterior  es suficiente.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +Agregar dependencia log42:
Por lo que veo en esta parte estás sugiriendo como se configura build.gradle. pero  nunca lo indicas, asi de trancazo pones el código.
Antes de pasar a la parte de gradle, creo que deberías explicar  el contenido del archivo properties.  Por ejemplo, qué significa *status* , ¿qué otras  opciones existen?.
La configuración de gradle debería ir en otra sección.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +### Descripción LogManager
Agregar numeración, la  palabra *Descripción* sale sobrando.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Esta clase es usada por el cliente de la aplicación para solicitar las instancias de logger.
¿ por qué usas la palabra *cliente* ?  Existe un cliente y un servidor? ¿a qué te refieres con solicitar ?  Un cliente solicita  una instancia ?... no me queda claro.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Gestiona la configuración de logging framework, este se encarga de leer la configuración inicial que se tendra en las bitácoras de la aplicación.
Mejorar esta traducción:  Gestiona la configuración de logging framework

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Contiene configuración default, sí no se especifica alguna en particular.
Sugiero:  Define la configuración que es aplicada por default.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Se carga durante el inicio del aplicativo pero no se puede modificar subsecuentemente cargado.
.. inicio de la aplicación,  no es posible modificarla posteriormente.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +#
quitar este caracter.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +* Ejecutar la siguiente clase para confirmar que la configuración anterior sea correcta.
Sugiero:
##### Ejemplo:   Clase que permite validar la configuración de Log4J2.
No usar LOGGER. Se ve muy agresivo. ¿Que te parece   `logger` ?

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/docs/log4j2-tutorial.md
> +
Cuando se acabe el modulo agrega lo siguiente para no dar la sensación que el documento está incompleto:
##### fin de modulo.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Agregar este archivo a .gitignore y ver si funciona en el STS

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/.project
> +<projectDescription>
Agregar este archivo a .gitignore y ver si funciona en el STS

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/.settings/org.eclipse.buildship.core.prefs
> +connection.project.dir=
Agregar este archivo a .gitignore y ver si funciona en el STS

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/.settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
Agregar este archivo a .gitignore y ver si funciona en el STS

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/build.gradle
> +/*
Quitar estos comentarios.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/build.gradle
> +    // Apply the java-library plugin to add support for Java Library
Quitar comentario. Para este documento se asume que se sabe o se tiene conocimiento de gradle.

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/build.gradle
> +    jcenter()
Quitar comentarios

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/settings.gradle
> +/*
sugiero que el proyecto se llame  examples-log4j2

2019-06-15 20:24 UTC, jorgerdc commented on log4j2/example-log4j2/src/main/java/log4j2/HelloWorldLog4j2.java
> + * configuration.
... some log levels taking a properties file as the source of configuration.

2019-07-21 20:45 UTC, alexJava2015 commented on log4j2/docs/log4j2-tutorial.md
> +* No permite multiples implementaciones.
Es correcto la palabra "no", ya que solo puedes hacer uso de una sola implementación a la vez, no se pueden hacer híbridas.

2019-07-21 22:10 UTC, alexJava2015 commented on log4j2/example-log4j2/build.gradle
> +/*
Se eliminaron comentarios correspondientes.

2019-07-21 22:11 UTC, alexJava2015 commented on log4j2/example-log4j2/build.gradle
> +    // Apply the java-library plugin to add support for Java Library
Se eliminaron comentarios correspondientes.

2019-07-21 22:11 UTC, alexJava2015 commented on log4j2/example-log4j2/build.gradle
> +    jcenter()
Se eliminaron comentarios correspondientes.

2019-07-21 22:39 UTC, alexJava2015 commented on log4j2/docs/log4j2-tutorial.md
> +* Para esta versión se tienen diversas `appenders` para poder configurar la bitácora de una manera más clara y consciza, a continucación se listan algunos:
Se mueve contenido a una sección independiente de configuración, ya que como mencionas debe ser un tema por separado para una mejor expliación.

2019-07-21 22:44 UTC, alexJava2015 commented on log4j2/docs/log4j2-tutorial.md
> +### Ecosistema
Se modifica sección para tener más clara la esencia de la configuración.

2019-07-21 22:45 UTC, alexJava2015 commented on log4j2/docs/log4j2-tutorial.md
> +* En la siguiente liga se encuentrar la configuración tradicional y appenders mencionados en el punto anterior: https://logging.apache.org/log4j/2.x/maven-artifacts.html
Se corrige falta ortográfica.

2019-07-23 04:10 UTC, alexJava2015 commented on log4j2/docs/log4j2-tutorial.md
> +* En la siguiente liga se encuentrar la configuración tradicional y appenders mencionados en el punto anterior: https://logging.apache.org/log4j/2.x/maven-artifacts.html
No aplica, porque se mueve esta sección a una independiente (se retomará posteriormente).

2019-08-14 17:24 UTC, closed without merging