Actualización STS workspace.
jorgerdc/tutoriales pull request #19
Opened 2019-08-11 03:28 UTC by jorgerdc

- Se actualiza  y se renombran el workspace para Eclipse/STS.
- Se agrega una sección al documento md para hacer referencia
a la existencia  archivo zip y se agrega 1 configuración
adicional para STS que no se pueden realizar en el WS, por lo que se debe hacer manual.
- Se actualiza el header de los archivos Java para que el texto referente a la Licencia de uso
del software sea genérica.
- Se actualizan los templates para el manejo del logger. Ahora se emplea Log4j 2 en lugar de SLF4J.

2019-08-18 20:01 UTC, alexJava2015 requested changes

2019-08-18 20:01 UTC, alexJava2015 commented on lineamientos-desarrollo/eclipse/configuracion-eclipse-ws.md
> +	* Agregar las siguientes líneas en negritas, justo después de la instrucción `openFile`
Modificar el texto, según lo acordado, en el cual se menciona no se puede poner como negritas porque esta dentro de una sección de "bash".

2019-08-18 20:01 UTC, alexJava2015 commented on lineamientos-desarrollo/eclipse/configuracion-eclipse-ws.md
>  * `template-logdef.xml`
Estaría bien poner la liga de descarga de los archivos.

2019-09-26 19:50 UTC, jorgerdc commented on lineamientos-desarrollo/eclipse/configuracion-eclipse-ws.md
> +	* Agregar las siguientes líneas en negritas, justo después de la instrucción `openFile`
corregido.

2019-09-26 19:50 UTC, jorgerdc commented on lineamientos-desarrollo/eclipse/configuracion-eclipse-ws.md
>  * `template-logdef.xml`
Estos archivos ya van incluidos en el WS, entonces ya no son necesarios.

2019-09-26 21:33 UTC, alexJava2015 approved these changes

2019-09-26 21:41 UTC, merged