Adding github guidelines
jorgerdc/tutoriales pull request #2
Opened 2019-01-03 20:51 UTC by jorgerdc

This is a MD document which included the git and github guidelines to create branches, pull and push changes and make pull request to review code.
Something that I think we need to update in this document is an explanation to create branches using the upstream repo. For example,  I'm the owner of this repo, so I don't need a fork.  I just created a branch.  My origin and upstream repo are pointing  to the same repo  (this repo - our main repo).   This works fine, but we need to discuss and agree if this is  fine or a better strategy should be used.

2019-01-05 21:49 UTC, alexJava2015 requested changes
Review 1

2019-01-05 21:49 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
Test

2019-01-05 21:53 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
Ok, la prueba funcionó!

2019-01-05 21:55 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
Seguimiento a la prueba. ;P

2019-01-05 21:58 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
ok, seguimiento a la prueba 2.

2019-01-05 22:10 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
Prueba seguimiento tres. ..

2019-01-05 22:11 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
prueba seguimiento  4

2019-01-05 22:12 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
cerrando conversación y prueba.

2019-01-13 01:59 UTC, alexJava2015 requested changes

2019-01-13 01:59 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +El primer paso para contribuir al desarrollo de un proyecto es la creación de un fork. Un Fork es una copia de un repositorio que se almacena localmente.
Tal vez habría que especificar que un fork es: "copia de master del proyecto origen del propietario o institución"

2019-01-13 01:59 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +git branch <nombre_branch>
Al parecer este comando: "git branch" debe ir antes del texto: "El siguiente paso es crear un nuevo branch y cambiarse a él. Ejecutar:" 
@jorgerdc

2019-01-13 01:59 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Cambiarse al branch master del fork:
Antes de esto, creo deberíamos mencionar el comando "git stash", este sirve para mantener el estado de los cambios que estemos realizando antes de actualizar el branch, esté, es temporal, se crea un index y no es necesario  realizar un commit.
Una vez que se tinen los cambios guardados de forma temporal se puede actualizar el branch con el comando "git pull upstream master" estando en brnach master, posteriormente se nos debemos cambiar al branch donde estabamos trabajando, siguiente paso sera sincronizar de master con nuestro branch usando el comando "git rebase master" con esto se tienen sincronizados los cambios, ahora hay que colocar nuestros cambios que tenemos en memoria para continuar trabajando, utilicemos el comando "git stash apply" con esto sincronizamos los cambios de memoria con la ultima vérsion de los comandos previamente ejecutados.
@jorgerdc

2019-01-13 01:59 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +![branch.png](https://raw.githubusercontent.com/jorgerdc/tutoriales/master/lineamientos-desarrollo/img/branch.png)
Tal vez la imagen estaría bien mostrar en el combo en vez de master el nuevo para mayor claridad.
@jorgerdc

2019-01-13 03:26 UTC, alexJava2015 requested changes

2019-01-13 03:26 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Para crear un pull request se hará uso de GitHub.
Agregar sección de datos previos para generar el PR,.
Una vez terminando los cambios y estemos seguros de lo que se quiere subir, ejecutar los comandos:
"git add -A" Agrega un index a los archivos para ser enlazados al repositorio.
"git commit" Enlista los archivos modificados y nuevos para asignar un comentario sobre dicha tarea.

Posterior a esto se ejecuta el comando previamente explicado: "git push origin nameBranch"

2019-01-13 03:26 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Notar que del lado derecho se configura la lista de revisores que deberán participar en la revisión. Es muy ***importante*** configurar esta sección.
No es clara la imagen con la descripción del texto en la parte de los revisores.

2019-01-13 03:26 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Una vez que todos los cambios han sido aplicados y todos los involucrados estén de acuerdo, el revisor puede marcar al branch como aprobado.
Podríamos agregar una imagen donde se muestre el signo de más para agregar el comentario sobre el código..

2019-01-13 03:26 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
Podemos agregar un apartado para mencionar la parte de "ssh key" para que contemplen la configuración como pre requisito tal vez antes de la explicación:
Liga con todo lo necesario para esta sección creo no es necesario explicarlo aquí, solo poner la liga:
https://help.github.com/articles/connecting-to-github-with-ssh/

2019-01-19 01:38 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +El primer paso para contribuir al desarrollo de un proyecto es la creación de un fork. Un Fork es una copia de un repositorio que se almacena localmente.
ok, corregido.

2019-01-19 01:46 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +git branch <nombre_branch>
corregido.

2019-01-19 01:54 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Cambiarse al branch master del fork:
Ok, este paso lo entiendo como una especie de "respaldo temporal". Solo tengo 2 preguntas..
1. Mencionas que no es necesario hacer un commit. Pero, commit  ¿de qué? Si observas, en esta sección nunca estamos proponiendo hacer un commit 
2. ¿cuál es el beneficio de incorporar estas 2 instrucciones? ¿qué riesgo se tendría si lo dejamos como está?

2019-01-19 01:58 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +![branch.png](https://raw.githubusercontent.com/jorgerdc/tutoriales/master/lineamientos-desarrollo/img/branch.png)
No entendí ¿cuál nuevo ?,  te refieres a que en el combo se muestre el nombre del branch ¿?

2019-01-19 02:04 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Notar que del lado derecho se configura la lista de revisores que deberán participar en la revisión. Es muy ***importante*** configurar esta sección.
No entendí. ¿te refieres a la imagen pull2.png? el enfoque de esta imagen no son los revisores. El enfoque es que se vea el botón "Create pull Request".
O podrías ser más específico en cuanto a lo que no se entiende? ¿qué le quito o qué le agrego?

2019-01-19 03:22 UTC, jorgerdc reviewed
Comentarios agregados.

2019-01-19 03:22 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Hacer clic en el botón “New Pull Request”.  Se deberá realizar la siguiente configuración en la que se indica que los cambios del branch se integrarán a master del repositorio principal (upstre
test

2019-01-19 03:22 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Para crear un pull request se hará uso de GitHub.
Ok, agregado, generé  una nueva sección: 1.6.1 Revisar de favor.

2019-01-19 03:22 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Una vez que todos los cambios han sido aplicados y todos los involucrados estén de acuerdo, el revisor puede marcar al branch como aprobado.
Listo, Se agregó mas detalle y 2 imágenes.

2019-01-19 05:21 UTC, jorgerdc reviewed
Listo, agregué sugerencia del comentario 1.
Subiré nuevo commit en un momento.

2019-01-19 05:21 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +### 1.1 Introducción
Ok, agrego esta liga,  lo pongo como algo opcional.

2019-01-19 05:26 UTC, alexJava2015 approved these changes
Done!

2019-01-19 05:26 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Cambiarse al branch master del fork:
Lo comento, porque sí quieres actualizar el branch y tienes cambios en el local debes hacer estas acciones para garantizar la sincronización de la ultima vérsion de master con el branch.

El riesgo solo es, que no tendrías sincronizados los cambios de master en tu branch cuando tienes cambios realizados "en tu branch local" y deseas empatarlos.

2019-01-19 05:39 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Cambiarse al branch master del fork:
Mmm sigo sin entender.
¿a qué te refieres con  "Tienes cambios en el local" ¿quién es el local?
Se supone que para actualizar los cambios del branch con master está la instrucción 
"git rebase master" mas las otras instrucciones que están documentadas en la sección 1.6.2, entonces sigo sin entender la idea de estas instrucciones.

2019-01-19 05:47 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Notar que del lado derecho se configura la lista de revisores que deberán participar en la revisión. Es muy ***importante*** configurar esta sección.
Ahh esta bien, sí es para mostrar solo lo del PR esta bien, pero entonces faltaría una para los revisores, para que sea más claro.

2019-01-19 05:56 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +![branch.png](https://raw.githubusercontent.com/jorgerdc/tutoriales/master/lineamientos-desarrollo/img/branch.png)
Analizando creo esta bien, tu quieres explicar como se muestra el nuevo branch creado, cierro el comentario, veo adecuada la imagen.

2019-01-19 06:14 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Cambiarse al branch master del fork:
Tal vez entonces podríamos poner esto en la sección 1.6.2 porque es parte de como tener sincronizados los cambios en tu local master con cualquier branch, en el escenario cuando por ejemplo: generas un PR, y sigues trabajando mientras hacen merge, entonces en ese momento tu ya tienes cambios en tu maquina pero no tienes los ultimos cambios de cuando se haga merge, entonces para sincronizar  los branches, te tienes que ir a master para bajar los cambios con pull sin embargo  hay que guardar de forma temporal los cambios que ya tenemos, que son lo comandos que comento arriba.

2019-01-19 06:14 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Para crear un pull request se hará uso de GitHub.
No logro ver la sección que mencionas, si me pudieras compartir el link para poderlo revisar.

2019-01-22 00:38 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +![branch.png](https://raw.githubusercontent.com/jorgerdc/tutoriales/master/lineamientos-desarrollo/img/branch.png)
ok cierra la conversación please.

2019-01-22 00:41 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Para crear un pull request se hará uso de GitHub.
está en mi penúltimo commit:  https://github.com/jorgerdc/tutoriales/pull/2/commits/0d40ed242b733ad1255965c14e0dab658d17e019  
Revisa por favor cada uno de los commits que mando. Ahí puedes ver los deltas con los cambios nuevos.

2019-01-22 00:43 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Notar que del lado derecho se configura la lista de revisores que deberán participar en la revisión. Es muy ***importante*** configurar esta sección.
¿qué faltaría? se más claro por favor. Especifica exactamente lo que observas que falta. No dejes enunciados ambiguos.

2019-01-22 00:44 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Cambiarse al branch master del fork:
Ok, ya entendí, revisé la documentación. Haré pruebas e integraré una nueva sección

2019-01-22 22:22 UTC, alexJava2015 approved these changes

2019-01-23 00:02 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Notar que del lado derecho se configura la lista de revisores que deberán participar en la revisión. Es muy ***importante*** configurar esta sección.
No faltaría agregar una imagen para los revisores o en que sección quedaría esta parte sí es que lo vamos a mencionar.

2019-01-24 04:17 UTC, alexJava2015 approved these changes

2019-01-24 05:18 UTC, jorgerdc commented
Adding github-guidelines.md

2019-01-24 05:26 UTC, merged