Se agrega temario.
jorgerdc/tutoriales pull request #26
Opened 2020-05-07 22:47 UTC by alexJava2015

Archivo con la lista de temas que se consideran importantes para aprender la tecnología ReactJS.

2020-05-08 00:07 UTC, jorgerdc requested changes

2020-05-08 00:07 UTC, jorgerdc commented on temario.md
> +# React JS (v16.13.1)
No hacer cop y & paste del temario oficial
Pasarlo a español a medida de lo posible.
Sugiero solo agregar los temas principales del 1 al 12 y ya después lo vamos mejorando.
Emplear el  mismo formato de los documentos modulo01.md, etc.

2020-05-09 04:56 UTC, alexJava2015 commented on temario.md
> +# React JS (v16.13.1)
Se subén cambios  solicitados, se cambia de ubicación para que este dentro de la carpeta correspondiente.

2020-05-09 15:35 UTC, jorgerdc commented on temario.md
> +# React JS (v16.13.1)
Ok, resuelto.

2020-05-09 15:36 UTC, jorgerdc requested changes
Revisar los comentarios y corregir.

2020-05-09 15:39 UTC, jorgerdc requested changes
Actualización de mensajes.

2020-05-09 15:39 UTC, jorgerdc commented on reactjs/docs/temario.md
> +### 2.1 Elementos en ReactJS
Ok. Podrías de favor hacer que los temas del 1 al 5 coincidan con los módulos que ya están desarrollados ? Es que los temas 1 a 5 están resumidos en los 3 primeros módulos y por lo tanto la numeración ya no coincide. Revisa por favor los módulos y hacerlos coincidir con esta numeración.

2020-05-09 15:39 UTC, jorgerdc commented on reactjs/docs/temario.md
> +## 8. Listas y claves
De aquí hacia adelante ya no hay numeración en los subtemas ?

2020-06-30 03:06 UTC, jorgerdc approved these changes

2020-06-30 03:06 UTC, merged