Se agrega modulo 1 para el tutorial de git
jorgerdc/tutoriales pull request #28
Opened 2020-05-27 00:22 UTC by jorgerdc

2020-06-02 05:07 UTC, alexJava2015 requested changes

2020-06-02 05:07 UTC, alexJava2015 commented on git/modulo01.md
> +* Se emplea el comando `git config` el cual permite configurar los valores de variables empleadas para el correcto funcionamiento de Git.
Creo estaría bien especificar para que sirven los datos de la configuración y sí deben o no coincidir con la cuenta que accesa a git hub.

2020-06-02 05:07 UTC, alexJava2015 commented on git/modulo01.md
> +	* Se deben propoporcionar credenciales de autenticación cada vez que se requiera hacer un `push` o un `pull`. Para solucionar lo anterior existen 2 estrategias:
Como se menciona que existen dos estrategias, creo sería bueno enumerar cuales son para que sea más claro y poderlas distinguir.

2020-08-01 21:26 UTC, jorgerdc commented on git/modulo01.md
> +* Se emplea el comando `git config` el cual permite configurar los valores de variables empleadas para el correcto funcionamiento de Git.
corregido.

2020-08-01 21:31 UTC, jorgerdc commented on git/modulo01.md
> +	* Se deben propoporcionar credenciales de autenticación cada vez que se requiera hacer un `push` o un `pull`. Para solucionar lo anterior existen 2 estrategias:
se corrige la redacción para evitar la confusión que las opciones no se han especificado.

2020-08-01 23:25 UTC, closed without merging

2020-08-02 03:44 UTC, alexJava2015 commented on git/modulo01.md
> +* Se emplea el comando `git config` el cual permite configurar los valores de variables empleadas para el correcto funcionamiento de Git.
Se cierra comentario.

2020-08-02 03:44 UTC, alexJava2015 commented on git/modulo01.md
> +	* Se deben propoporcionar credenciales de autenticación cada vez que se requiera hacer un `push` o un `pull`. Para solucionar lo anterior existen 2 estrategias:
Se cierra comentario.