Dev jorge junit5 start
jorgerdc/tutoriales pull request #3
Opened 2019-01-26 23:35 UTC by jorgerdc

This  is the first PR about JUnit5.   It contains  documentation and examples  of modules 1 to 4.  Next modules will be included in  future PRs.
Please @alexJava2015   join as a reviewer.

2019-02-04 04:55 UTC, alexJava2015 requested changes

2019-02-04 04:55 UTC, alexJava2015 commented on junit5/docs/modulo01.md
> +@Retention(RUNTIME)
Creo se debe explicar el porque de la anotación para mayor claridad.

2019-02-04 04:55 UTC, alexJava2015 commented on junit5/docs/modulo01.md
> +@Target({ TYPE, METHOD })
Creo se debe explicar el porque de la anotación para mayor claridad.

2019-02-04 04:55 UTC, alexJava2015 commented on junit5/docs/modulo01.md
> +  // no code
Deberíamos agregar un comportamiento básico para poder ver realmente como funciona esta parte.

2019-02-05 00:37 UTC, alexJava2015 requested changes

2019-02-05 00:37 UTC, alexJava2015 commented on junit5/docs/modulo02.md
> +* Un método de prueba es aquel anotado directamente o meta-anotado  con alguna de las siguientes anotaciones: `@Test`, `@RepeatedTest`, `@ParameterizedTest`, `@TestFactory`, o `@TestTemplate`
Sería bueno poner una liga para ver la documentación de cada una de las anotaciones.

2019-02-05 00:37 UTC, alexJava2015 commented on junit5/docs/modulo02.md
> +public class TestMethods {
Sería bueno agregar la descripción general de que trata la prueba para tener algo de contexto, aunque al final se explican detalles del código creo se simplificaría saber de que trata la prueba.

2019-02-05 00:37 UTC, alexJava2015 commented on junit5/docs/modulo02.md
> + @FunctionalInterface
Documentar de forma breve la interfaz, de ser posible las líneas importantes como: @API., etc.

2019-04-28 06:10 UTC, jorgerdc commented on junit5/docs/modulo01.md
> +@Retention(RUNTIME)
Mmm creo que deberíamos dejarlo así como está.
La explicación que solicitas no es propia de JUnit.   Estas anotaciones se usan para indicarle al compilador de Java que la clase va a actuar como anotación.  Es decir, es la sintaxis que se usa en Java para definir una anotación.    Aquí se asume que ya se tiene el conocimiento previo para definir o crear una anotación.  La creación de anotaciones es parte del la documentación de Java 5 que fue donde se incorporaron al lenguaje.
¿ Estás de acuerdo que este tipo de antecedentes no deberían documentarse aquì ?  Si el lector no entiende como se crea una anotación, lo correcto es que el lector consulte la documentación  del JDK.

2019-04-28 06:11 UTC, jorgerdc commented on junit5/docs/modulo01.md
> +@Target({ TYPE, METHOD })
Mismo comentario con respecto al anterior.

2019-04-28 06:12 UTC, jorgerdc commented on junit5/docs/modulo01.md
> +  // no code
No entendí el comentario. ¿qué debo agregar?  ¿a qué te refieres con agregar comportamiento básico ?

2019-04-28 06:18 UTC, jorgerdc commented on junit5/docs/modulo02.md
> +* Un método de prueba es aquel anotado directamente o meta-anotado  con alguna de las siguientes anotaciones: `@Test`, `@RepeatedTest`, `@ParameterizedTest`, `@TestFactory`, o `@TestTemplate`
Mmm todo esto está en la documentación oficial de Junit5 en el Javadoc. Entonces no creo que sea necesario, ya que si agrego ligas, tendría que hacerlo para todas las clases que mencione en en tutorial. Se asume que si el lector desea conocer más detalle de alguna clase,  deberá revisar el Javadoc.  Generalmente esto sucede cuando estás aprendiendo a usar un API nuevo. ¿estas de acuerdo ?

2019-04-28 06:20 UTC, jorgerdc commented on junit5/docs/modulo02.md
> +public class TestMethods {
Mmm según yo,  el enunciado "Ciclo de vida de una clase de prueba" es suficiente para saber a nivel general de qué trata la prueba.  O tienes algún texto propuesto ?

2019-04-28 06:27 UTC, jorgerdc commented on junit5/docs/modulo02.md
> + @FunctionalInterface
La documentación de esta interface está en el  javadoc de Junit. Considero que no tendría mucho caso documentar aquí nuevamente. ¿ no crees ?

2019-08-07 01:04 UTC, alexJava2015 commented on junit5/docs/modulo01.md
> +@Retention(RUNTIME)
Sí, tienes razón, no debemos poner esto, debido a que ya es algo que se debería de saber.
Cerrado.

2019-08-07 01:04 UTC, alexJava2015 commented on junit5/docs/modulo01.md
> +@Target({ TYPE, METHOD })
De acuerdo con el comentario anterior, se cierra el caso.

2019-08-08 00:50 UTC, alexJava2015 requested changes

2019-08-08 00:50 UTC, alexJava2015 commented on junit5/docs/modulo02.md
> +* Un método de prueba es aquel anotado directamente o meta-anotado  con alguna de las siguientes anotaciones: `@Test`, `@RepeatedTest`, `@ParameterizedTest`, `@TestFactory`, o `@TestTemplate`
De acuerdo, como comentas se podrían poner pero es algo que lo debe hacer cada desarrollador que desee conocer más del tema.
Caso cerrado.

2019-08-08 00:50 UTC, alexJava2015 commented on junit5/docs/modulo02.md
> +public class TestMethods {
No recuerdo bien porque del comentario que realice, pero basta con lo que pusiste.
Caso cerrado.

2019-08-08 00:50 UTC, alexJava2015 commented on junit5/docs/modulo02.md
> + @FunctionalInterface
Sí, realmente no tiene razón de ponerlo de nuevo.

2019-08-08 01:41 UTC, alexJava2015 commented
> This is the first PR about JUnit5. It contains documentation and examples of modules 1 to 4. Next modules will be included in future PRs.
> Please @alexJava2015 join as a reviewer.

2019-08-08 01:41 UTC, closed without merging