Se agrega módulo 4 tutorial ReactJS
jorgerdc/tutoriales pull request #30
Opened 2020-07-01 04:40 UTC by jorgerdc

Manejo de eventos.

2020-07-04 04:42 UTC, alexJava2015 requested changes

2020-07-04 04:42 UTC, alexJava2015 commented on reactjs/docs/modulo04.md
> +* Si se hace uso de una clase ES6,  por convención el método que maneja al evento se define como un método de la clase.
Sería bueno poner el link de la descripción para "ES6" por ser tema nuevo, sería importante tener contexto.

2020-07-09 03:57 UTC, jorgerdc commented on reactjs/docs/modulo04.md
> +* Si se hace uso de una clase ES6,  por convención el método que maneja al evento se define como un método de la clase.
Ok, se agrega liga para poder ver la definición de una clase en ES6

2020-07-09 05:13 UTC, alexJava2015 approved these changes

2020-07-09 15:54 UTC, merged