ReactJS - Se agrega modulo 05
jorgerdc/tutoriales pull request #32
Opened 2020-07-13 23:37 UTC by jorgerdc

2020-07-14 04:56 UTC, alexJava2015 requested changes

2020-07-14 04:56 UTC, alexJava2015 commented on reactjs/docs/modulo05.md
> +* Es posible realizar la definición  de varios componentes que encargados de encapsular cierto comportamiento.
Según recuerdo cada punto debe describir algo, en este punto es confuso, parece esta incompleta la idea.

2020-07-14 04:56 UTC, alexJava2015 commented on reactjs/docs/modulo05.md
> +* En este ejemplo se crea una expresión booleana  `boolean && expression` la cual en javascript evalúa a `expression`
Corregir la ortografía en "la expression"

2020-07-17 00:02 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +* Es posible realizar la definición  de varios componentes que encargados de encapsular cierto comportamiento.
Se agrega más detalle y se mejora la redaccón.

2020-07-17 00:03 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +* En este ejemplo se crea una expresión booleana  `boolean && expression` la cual en javascript evalúa a `expression`
No es error. Creo que leíste mal. Agregaré `:`para que sea más claro.

2020-07-19 04:13 UTC, alexJava2015 submitted a review, later dismissed

2020-07-20 20:02 UTC, rodrigofrancisco commented on reactjs/docs/modulo05.md
> +```
Se repite "operando izquierdo" sin ninguna razón aparente. Además, se repite dos veces "expresión booleana" en la oración por lo que se sugiere reescribir la oración como: 

"Es posible escribir expresiones booleanas cuyo operador izquierdo sea cualquier expresión que se evalue a verdadedo o falso en Javascript. Para renderizar un componente por medio de un `inline-if` es necesario encerrar la expresión JSX entre `{ }`. A nivel general la sintaxis queda de la siguiente forma:

```jsx
{expresionBooleanaEnJS && <expresionJSX>...</expresionJSX> }
```
* Observa  que después de la expresión booleana se debe escribir el operador lógico `&&` seguido de la expresión a renderizar si la condición se evalua a `true`.

2020-07-20 22:59 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +```
Corregido

2020-07-21 03:40 UTC, rhofp commented on reactjs/docs/modulo05.md
>  {expresionBooleanaEnJS} && <expresionJSX>...</expresionJSX>
Disculpen la insistencia pero la llave que cierrra debe ir al final de `</expresionJSX>`, es decir:
```jsx
{expresionBooleanaEnJS && <expresionJSX>...</expresionJSX> }
```

2020-07-21 03:41 UTC, rhofp commented on reactjs/docs/modulo05.md
> +* Observar que después de la expresión booleana se escribe el operador lógico  `&&`  seguido de la expresión a renderizar cuando la condición se evalua a  `true`.
Debe de ir arriba del subtitulo **Ejemplo**.

2020-07-21 03:42 UTC, rodrigofrancisco requested changes
Últimas correcciones :s y ya quedaría xd jajaja.

2020-07-21 04:33 UTC, jorgerdc commented on reactjs/docs/modulo05.md
>  {expresionBooleanaEnJS} && <expresionJSX>...</expresionJSX>
No, al contrario, gracias por la revisión y por colaborar. Las revisiones que sean necesarias :)  
Resuelto.

2020-07-21 04:33 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +* Observar que después de la expresión booleana se escribe el operador lógico  `&&`  seguido de la expresión a renderizar cuando la condición se evalua a  `true`.
Resuelto

2020-07-21 20:04 UTC, rodrigofrancisco approved these changes

2020-07-22 01:22 UTC, merged