ReactJS - Se agrega el módulo  6
jorgerdc/tutoriales pull request #33
Opened 2020-07-17 02:13 UTC by jorgerdc

2020-07-17 04:31 UTC, rhofp commented on reactjs/docs/modulo05.md
> +* Es posible escribir expresiones booleanas y operadores lógicos como `&&`, `||`, etc.
Yo tengo entendido que solo se puede utilizar el operador lógico `&&` para sentencias `inline if`, porque si se indica que se pueden utilizar todos los operadores lógicos uno podría pensar que lo siguiente es posible:
```jsx
return (
    <div>
      <h1>Bandeja de entrada</h1>
      { numEmailsSinLeer >0 ||
        <h2>Usted tiene {numEmailsSinLeer} emails nuevos.</h2>
      }
      { numEmailsSinLeer==0 ||
        <h2>Felicidades! No tiene correos por leer.</h2>
      }
    </div>
  );
```
Lo cual, de acuerdo con mi lógica sería incorrecto.
Obviamente lo que si se podría hacer sería poner tantos operadores lógicos como uno quisiera en la expresión booleana que precede a `&&`, pero insisto, la redacción me hace pensar que puedo poner `||`o `!` después de la expresión booleana.

2020-07-17 04:40 UTC, rhofp commented on reactjs/docs/modulo05.md
> +```
Recomiendo cambiar este ejemplo por el siguiente (Obviamente con su debida traducción)
```jsx
render() {
  const isLoggedIn = this.state.isLoggedIn;
  return (
    <div>
      {isLoggedIn        ? <LogoutButton onClick={this.handleLogoutClick} />
        : <LoginButton onClick={this.handleLoginClick} />      }
    </div>  );
}
```
Considero que este ejemplo es mejor porque continua con la línea anterior, en la cual se trabaja la renderización de componentes y no de solo cadenas.
Un camino alternativo sería indicar que, es posible rescribir el ejemplo de`MailBox` utilizando el operador ternario y poner eso en lugar de este ejemplo

2020-07-17 04:49 UTC, rhofp commented on reactjs/docs/modulo06.md
> +* La asignación de la *key*  a cada elemento de la lista se dene realizar cuando se escribe el elemento JSX en lugar de hacerlo con los elementos  HTML estándar.
Pequeños errores de dedo.  :smile: 
* Cambiar "lisa" por "lista"
* Sustituir "dene" por "debe"

2020-07-17 05:01 UTC, rodrigofrancisco requested changes
¡Hola! 
Realicé dos cosas:
* Observaciones a dos de los snippets proporcionados en el módulo 5.
* Señale algunos errores de dedo del módulo 6.

Saludos!

2020-07-19 00:38 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +* Es posible escribir expresiones booleanas y operadores lógicos como `&&`, `||`, etc.
En términos de sintaxis, el operador || también fue valido, sin embargo tienes razón. Lo correcto es utilizar solo && siempre ya que de otra forma el uso de || implica que el resultado sea siempre la propia expresión JSX y por lo tanto se mostraría su contenido y la condición ya no tendría sentido. Corregiré este detalle.

2020-07-19 00:58 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +```
Ok, de acuerdo, aplico la sugerencia.

2020-07-19 01:00 UTC, jorgerdc commented on reactjs/docs/modulo06.md
> +* La asignación de la *key*  a cada elemento de la lista se dene realizar cuando se escribe el elemento JSX en lugar de hacerlo con los elementos  HTML estándar.
corregido ! gracias :)

2020-07-20 19:43 UTC, rodrigofrancisco submitted a review, later dismissed
Ya le di click en aprobado, pero me surgió la duda
```jsx
  <OrdenCompra productos {productos}/>,  
```
Es la línea 104, debería haber un `=` ? 
Fuera de eso, creo que ya quedó este módulo :+1: 

Ok, gracias, ya fue corregido.

2020-07-20 20:33 UTC, alexJava2015 submitted a review, later dismissed

2020-07-21 01:47 UTC, jorgerdc commented
@alexJava2015 @rhofp  De  favor podrían nuevamente revisar al corrección y aprobar ?
Debido al cambio que hice, me pide nueva aprobación.
Gracias.

2020-07-21 01:48 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +* Es posible escribir expresiones booleanas y operadores lógicos como `&&`, `||`, etc.
Resuelto.

2020-07-21 03:22 UTC, rodrigofrancisco approved these changes

2020-07-22 00:53 UTC, merged