Dev jorge reactjs modulo7
jorgerdc/tutoriales pull request #34
Opened 2020-07-19 01:18 UTC by jorgerdc

Revisar únicamente el commit 
[4787d75](https://github.com/jorgerdc/tutoriales/commit/4787d752331b66fba33141834853c15faf3c8112)
Los otros 2 commits ya fueron incluidos en otros PRs.

2020-07-20 20:09 UTC, rhofp commented on reactjs/docs/modulo07.md
> +* La forma estándar de realizar lo anterior es a través de un concepto llamado ***controlled components***.
* Falta un artículo en la primera viñeta, "En ReacJS, los formularios ..."
* En la segunda viñeta me gustaría agregar que se pueden mostrar una página nueva o simplemente recargar la página.

2020-07-20 20:46 UTC, rodrigofrancisco requested changes
Se solicitan, cambios mínimos, pero a mi parecer este módulo está prácticamente listo.
P. D. No sé cómo lo este manejando pero con ejercicio al lector se me ocurre poner el clásico formulario que solicite el país y la ciudad. Al seleccionar un país la lista de ciudades debe cambiar de acuerdo al país que seleccionó.

2020-07-21 04:31 UTC, rodrigofrancisco submitted a review, later dismissed

2020-07-22 04:00 UTC, alexJava2015 requested changes

2020-07-22 04:00 UTC, alexJava2015 commented on reactjs/docs/modulo07.md
> +* En un formulario, elementos como `<input>`, `<textarea>`, etc.,  mantienen un *estado interno*  que depende de los valores capturados por el usuario.
Sería bueno mencionar algunos ejemplos de dichos estados, de preferencia una liga hacia una página que los describa a detalle pata tener mayor referencia.

2020-07-22 04:00 UTC, alexJava2015 commented on reactjs/docs/modulo07.md
> +* A pesar de no contar con este atributo, ReactJS se emplea un atributo `value`para controlar el contenido del elemento:
Modificar el texto después de la coma " , " posibles textos:
En ReactJS se emplea . . . 
ReactJS emplea . . .

2020-07-22 21:47 UTC, jorgerdc commented on reactjs/docs/modulo07.md
> +* La forma estándar de realizar lo anterior es a través de un concepto llamado ***controlled components***.
Resuelto.

2020-07-22 21:50 UTC, jorgerdc commented on reactjs/docs/modulo07.md
> +* En un formulario, elementos como `<input>`, `<textarea>`, etc.,  mantienen un *estado interno*  que depende de los valores capturados por el usuario.
Mmm aquí no aplica.  EL estado de cada elemento del formulario depende de los valores que capture el usuario.  No hay como tal una lista de status.. Esto es similar al concepto de "estado de una instancia" en POO.  El estado de una instancia se adquiere al momento de inicializar sus atributos con valores partículares. Agregaré únicamente un texto para aclarar la idea y mejorar la redacción.

2020-07-22 21:53 UTC, jorgerdc commented on reactjs/docs/modulo07.md
> +* A pesar de no contar con este atributo, ReactJS se emplea un atributo `value`para controlar el contenido del elemento:
Corregido.

2020-07-22 22:00 UTC, alexJava2015 commented on reactjs/docs/modulo07.md
> +* En un formulario, elementos como `<input>`, `<textarea>`, etc.,  mantienen un *estado interno*  que depende de los valores capturados por el usuario.
Entiendo la idea, procedemos cerramos este comentario.

2020-07-22 22:11 UTC, alexJava2015 commented on reactjs/docs/modulo07.md
> +* A pesar de no contar con este atributo, ReactJS se emplea un atributo `value`para controlar el contenido del elemento:
Perfecto, se cierra comentario.

2020-07-22 22:58 UTC, alexJava2015 approved these changes

2020-07-23 00:11 UTC, merged