ReactJS - Se agrega módulo 09
jorgerdc/tutoriales pull request #36
Opened 2020-07-25 02:14 UTC by jorgerdc

2020-07-31 16:47 UTC, rhofp commented on reactjs/docs/modulo09/modulo09.md
> +* `npm`representa  aun repositorio online de paquetes en el que se pueden publicar 	proyectos Open Source escritos con Node.js. En el mundo Java el equivalente es un *Maven repository*.
Sobra una "a"

2020-07-31 16:49 UTC, rhofp commented on reactjs/docs/modulo09/modulo09.md
> +* Crear en caso de no existir el archivo `.npmrc` en el directorio `home`del usuario de desarrollo.  En el siguiente ejemplo e emplea `nano`, usar otro editor en caso de ser necesario.
Falto una "s" en la oración que dice "En el siguiente ejemplo" ...

2020-07-31 16:56 UTC, rodrigofrancisco requested changes
Solo encontre dos errores de dedo muy muy pequeños :p pero todo muy bien

2020-08-02 19:10 UTC, jorgerdc commented on reactjs/docs/modulo09/modulo09.md
> +* `npm`representa  aun repositorio online de paquetes en el que se pueden publicar 	proyectos Open Source escritos con Node.js. En el mundo Java el equivalente es un *Maven repository*.
resuelto

2020-08-02 19:11 UTC, jorgerdc commented on reactjs/docs/modulo09/modulo09.md
> +* Crear en caso de no existir el archivo `.npmrc` en el directorio `home`del usuario de desarrollo.  En el siguiente ejemplo e emplea `nano`, usar otro editor en caso de ser necesario.
corregido.

2020-08-04 04:37 UTC, alexJava2015 requested changes

2020-08-04 04:37 UTC, alexJava2015 commented on reactjs/docs/modulo09/modulo09.md
> +* En una *Single page ReactJS application*, la página es administrada completamente por ReactJS.
En ningún momento se menciona alguna de las características respecto a "multiple-page ReactJS", sería bueno poner al menos un link para documentarse al respecto o en su defecto listar algunas que se consideren importantes.

2020-08-04 04:37 UTC, alexJava2015 commented on reactjs/docs/modulo09/modulo09.md
> +* `package.json` Contiene las dependencias del proyecto.  Por ejemplo, se pude apreciar las dependencias que corresponden a ReactJS:
Corregir palabra "pude" apreciar... -> "puede" apreciar ...

2020-08-05 02:06 UTC, jorgerdc commented on reactjs/docs/modulo09/modulo09.md
> +* En una *Single page ReactJS application*, la página es administrada completamente por ReactJS.
Ok, se mejora la explicación de estos conceptos.

2020-08-05 02:08 UTC, jorgerdc commented on reactjs/docs/modulo09/modulo09.md
> +* `package.json` Contiene las dependencias del proyecto.  Por ejemplo, se pude apreciar las dependencias que corresponden a ReactJS:
corregido.

2020-08-06 02:05 UTC, jorgerdc commented
@alexJava2015   podrías de favor echarle un ojo rápido al segundo update ? Solo falta tu approval para hacer merge

2020-08-06 04:20 UTC, alexJava2015 approved these changes

2020-08-06 19:07 UTC, merged