Se realizan actualizaciones y mejoras
jorgerdc/tutoriales pull request #38
Opened 2020-08-04 01:10 UTC by jorgerdc

Estas actualizaciones se realizan para poder hacer uso del documento en el curso de SchoolBook.  Se quita el renglón que sugiere usar siempre Forks. Dependiendo el caso, puede emplearse cualquiera de las 2 técnicas:
* Colaboradores
* Contribuyentes

2020-08-06 02:03 UTC, jorgerdc commented
@alexJava2015 @rhofp  Chavos, de favor, podrían revisar los cambios del commit 
[b1ffae1](https://github.com/jorgerdc/tutoriales/pull/38/commits/0aa1a431e02ad5969f0c0b8d136c0c6702cb75d0)
Necesito hacer merge de este update para el curso de SchoolBook. Tengo planeado empezar la siguiente semana.

2020-08-06 03:56 UTC, rodrigofrancisco requested changes
La interfaz del reviewer ya no me dejo poner el comentario pero
En la sección 1.3.1, primera viñeta : "Antes de iniciar, acceder al sitio de GitHub, entrar a sesión, o crear una cuenta en caso de no existir."
No quiero entrar en debates filosóficos, pero, "en caso de no existir" no podría crear una cuenta jajaja bueno a lo que me refiero es que sugiero reescribir la oración como:
Antes de iniciar, acceder al sitio de GitHub, inicia sesión, o crear una cuenta en caso de no tener una."

2020-08-06 03:56 UTC, rhofp commented on lineamientos-desarrollo/github/github-guidelines.md
> +* De esta historia se deberán identificar los commits que se desean unificar, iniciando en orden cronológico: de arriba hacia abajo. En esta muestra, se ha identificado que los últimos 4 commits pert
Cambiar "trabando" por "trabajando", esta casi al final de este párrafo

2020-08-06 03:56 UTC, rhofp commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Al ejecutar el comando anterior, aparecerá un Wizard a nivel consola en el cual se deberán aplicar las configuraciones que se describen a continuación. Nota: el Wizard será mostrado en el editor de
Se recomienda poner Wizard entre comillas y con la "W" minúscula, es decir como "wizard" o en caso de querer traducirlo podría quedar como "... asistente a nivel de consola ..."

2020-08-06 03:56 UTC, rhofp commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Observar que al salir del editor, automáticamente se presentará un nuevo wizard. En esta ocasión se presenta un wizard para configurar los mensajes o descripción del commit unificado.
Mejor la redacción para no leer tanto "wizard" jaja. Tal vez sería bueno dejar la palabra "wizard" e intercalarla con la palabra "asistente".
O también se puede reescribir esta oración como : "Observar que al salir del editor, automáticamente se presentará un nuevo wizard para configurar los mensajes o descripción del commit unificado."

2020-08-06 03:56 UTC, rhofp commented on lineamientos-desarrollo/github/github-guidelines.md
> +* La siguiente imagen muestra la pantalla para crear un pull request (desde la página principal del repo upstream).
Aquí  "(desde la página principal del repo upstream)".
Sería desde el repo _fork_, no?
Porque sino el repo upstream no detectaría la rama que acabas de subir. A menos claro que ya estemos siguiendo el "workflow" de "collaborators" pero creo que eso no se específico.

2020-08-06 03:58 UTC, rhofp commented on lineamientos-desarrollo/github/github-guidelines.md
> +* La siguiente imagen muestra la pantalla para crear un pull request (desde la página principal del repo upstream).
o si los detecta? :o la verdad no recuerdo si los detecta. Según yo no.

2020-08-06 18:37 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* De esta historia se deberán identificar los commits que se desean unificar, iniciando en orden cronológico: de arriba hacia abajo. En esta muestra, se ha identificado que los últimos 4 commits pert
corregido.  También corregí la observación que no pudo ser agregada en el reviewer.

2020-08-06 18:38 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Al ejecutar el comando anterior, aparecerá un Wizard a nivel consola en el cual se deberán aplicar las configuraciones que se describen a continuación. Nota: el Wizard será mostrado en el editor de
corregido. Usé cursivas en lugar de comillas para homologar con otros casos.

2020-08-06 18:41 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* Observar que al salir del editor, automáticamente se presentará un nuevo wizard. En esta ocasión se presenta un wizard para configurar los mensajes o descripción del commit unificado.
corregido

2020-08-06 18:52 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* La siguiente imagen muestra la pantalla para crear un pull request (desde la página principal del repo upstream).
Algo curioso pasa aquí. Según recuerdo, justo después de hacer el push del branch te aparece la opción de crear el PR. Pero ya me hiciste dudar si es desde el upstream o desde el fork. Según yo, esa opción la ví desde el upstream.  Intenté hacerlo desde el upstream con un branch que fue subido al fork días atrás y ya no me puso la opción, y efectivamente se tendría que hacer desde el fork.  Para evitar esto, mejor le cambio al fork como sugieres.  Gracias -

2020-08-06 19:43 UTC, rhofp commented on lineamientos-desarrollo/github/github-guidelines.md
> +* La siguiente imagen muestra la pantalla para crear un pull request (desde la página principal del repo upstream).
¡Okaay, perfecto!

2020-08-06 19:44 UTC, rodrigofrancisco submitted a review, later dismissed

2020-08-07 00:16 UTC, alexJava2015 requested changes

2020-08-07 00:16 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +* La siguiente figura muestra la pantalla para revisión de código:
Sugiero agregar una nueva sección para separar la parte de modificación de archivos y separar los temas de PR y revisiones. Tal vez 1.8.3

2020-08-07 02:29 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +* La siguiente figura muestra la pantalla para revisión de código:
De acuerdo.
Corregido.

2020-08-07 02:38 UTC, alexJava2015 approved these changes

2020-08-07 17:23 UTC, merged