Se mejora y actualiza tutorial Bootstrap - Módulos 1, 2 y 3
jorgerdc/tutoriales pull request #40
Opened 2020-08-25 20:13 UTC by jorgerdc

Entre las mejoras, se actualizan las ligas para poder visualizar los ejemplos html a través del sitio de repositorio https://jorgerdc.github.io/tutoriales.   Las ligas funcionarán hasta que se haga merge de este PR a master.

2020-08-26 01:08 UTC, vservin requested changes
Verificar 11 cambios.

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo01.md
> +* Responsive meta-tag.   Bootstrap fue desarrollado al estilo *movile first* . Esto significa que su uso está optimizado para apps móviles y puede ser adaptado para escalar a aplicaciones web haciend
Corregir typos:

- [x] "al estilo *movile first*" cambiar a "al estilo *mobile first*"
- [x] "concepto de  ***CSS media quieries***" cambiar a "concepto de  ***CSS media queries***"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo02.md
> +* Los conteedores pueden anidarse aunque no es muy frecuente su uso.
Corregir typo "conteenedores" a "contenedores"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo02.md
> +* En la siguiente tabla se muestran las medidas y su uso por cada tipode container.
Corregir typo "tipode" a "tipo de"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-04.html)
La línea 169 y 170 es lo mismo, eliminar la el duplicado.

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo01.md
> +* El tamaño  total de un elemento con `border-box`incluye  los valores de las propiedades padding y border.  El navegador ajusta el tamaño del objeto para evitar sumar los valores de estas 2 propieda
Corregit typo "disenar" a "diseñar"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo01.md
> +* La medida del margen no se considera ya que no forma parte del tamaño del objeto, mas bien,  forma parte del espacio total que ocupará el objeto.
Corregir "mas bien" a "más bien"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo01.md
> +* Notar el uso de rutas relativas. Se asume que en la carpeta donde se encuentra la plantilla se encuentran las carpeta `bootstrap` descargada.
Corregir typo "las carpeta" a "la carpeta"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo03.md
> + <button type="sumbmit" class="btn btn-primary mb-2">Siguiente</button>
Corregir typo "sumbmit" a "submit"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo03.md
> +	* x - leff y right
Corregir typo "leff" a "left"

2020-08-26 01:08 UTC, vservin commented on bootstrap/docs/modulo03.md
>  ### 3.4 Dialogos modales.
Corregir "Dialogos" a "Diálogos"

2020-08-26 01:08 UTC, vservin commented on bootstrap/ejemplos/modulo03/form-example-05.html
>            <div class="custom-control custom-radio custom-control-inline" id="modalidad-radios">
duplicación de id "modalidad-radios", eliminar id

2020-08-26 01:46 UTC, alexJava2015 requested changes

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/contenedores.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/contenedores.html)
Corregir link corrupto

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-01.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-01.html)  Modificar el breakpoint y redimensionar la ventana del
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-03.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-03.html)  Modificar el estilo del contenedor  de `container-fluid
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-04.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-04.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-05.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-05.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-06.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-06.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-07.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-07.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* Observar que se trata de cuidar que la suma de las columnas + los offsets sea 12.
Si mal no entiendo se rompe el esquema de los 12 offset, esto porque se menciona que en la propiedad "_offset-x..x_" debe dar la suma, sin embargo en total da como resultado 19.
Tal vez interprete mal  cual es la propiedad, a como lo menciona el texto "**el asterisco indica en número de columna [1-12].**" debe ser 12 en offset-....

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-07.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-07.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo03.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo03/form-example-07.html)
Corregir link corrupto.

2020-08-26 01:46 UTC, alexJava2015 commented on bootstrap/docs/modulo03.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo03/form-example-07.html)
Corregir link corrupto.

2020-08-26 02:46 UTC, vservin commented on bootstrap/docs/modulo02.md
> +* Observar que se trata de cuidar que la suma de las columnas + los offsets sea 12.
@alexJava2015 En dónde comentas que la suma da como resultado 19? Creo que no entiendo bien tu duda.

2020-08-26 20:28 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* Responsive meta-tag.   Bootstrap fue desarrollado al estilo *movile first* . Esto significa que su uso está optimizado para apps móviles y puede ser adaptado para escalar a aplicaciones web haciend
Listo :)

2020-08-26 20:30 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* Los conteedores pueden anidarse aunque no es muy frecuente su uso.
Listo 👍

2020-08-26 20:30 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* En la siguiente tabla se muestran las medidas y su uso por cada tipode container.
listo 👍

2020-08-26 20:34 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-04.html)
Apuntan al mismo archivo, sin embargo en el primero se muestra el código fuente y el el segundo se hace el render del ejemplo, es decir, tal cual se vería  la página. Por esta razón estoy apuntando a https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02 la cual corresponde al sitio del repo.  Dicho enlace estará disponible hasta que se haga merge en master.  Espero haberme dado a entender.

2020-08-26 20:34 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* El tamaño  total de un elemento con `border-box`incluye  los valores de las propiedades padding y border.  El navegador ajusta el tamaño del objeto para evitar sumar los valores de estas 2 propieda
Listo 👍

2020-08-26 20:40 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* La medida del margen no se considera ya que no forma parte del tamaño del objeto, mas bien,  forma parte del espacio total que ocupará el objeto.
listo 👍

2020-08-26 20:43 UTC, jorgerdc commented on bootstrap/docs/modulo01.md
> +* Notar el uso de rutas relativas. Se asume que en la carpeta donde se encuentra la plantilla se encuentran las carpeta `bootstrap` descargada.
Listo 👍

2020-08-26 20:44 UTC, jorgerdc commented on bootstrap/docs/modulo03.md
> + <button type="sumbmit" class="btn btn-primary mb-2">Siguiente</button>
listo 😄

2020-08-26 20:45 UTC, jorgerdc commented on bootstrap/docs/modulo03.md
> +	* x - leff y right
listo 👍

2020-08-26 20:45 UTC, jorgerdc commented on bootstrap/docs/modulo03.md
>  ### 3.4 Dialogos modales.
listo 👍

2020-08-26 23:18 UTC, alexJava2015 commented on bootstrap/docs/modulo02.md
> +* Observar que se trata de cuidar que la suma de las columnas + los offsets sea 12.
En la propiedad de "offset-sm-X" si sumas los valores dan 19. Esa es la propiedad que yo entiendo deben dar 12 como máximo.

2020-08-26 23:59 UTC, vservin commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-04.html)
Si, si se dio a entender 👍🏻

2020-08-27 00:15 UTC, jorgerdc commented on bootstrap/ejemplos/modulo03/form-example-05.html
>            <div class="custom-control custom-radio custom-control-inline" id="modalidad-radios">
listo, corregido :)

2020-08-27 00:18 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/contenedores.html)
No encuentro error con la liga. Tal vez se debe a que este archivo no forma parte de este branch. Está en master. Al hacer merge debería solucionarse.

2020-08-27 00:23 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/contenedores.html)
Esta liga funcionará una vez que se haga merge en master.  Esto se debe a que el sitio del repo apunta a la rama master.

2020-08-27 00:24 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-01.html)
No encuentro error con la liga. Tal vez se debe a que aun no se hace merge ? Este link lo puedes validar en GitHub seleccionando el branch. Al hacer clic se muestra correctamente:. Osea, [aquí](https://github.com/jorgerdc/tutoriales/blob/dev-jorge-bootstrap-update/bootstrap/docs/modulo02.md)

2020-08-27 00:24 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-01.html)  Modificar el breakpoint y redimensionar la ventana del
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-03.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-03.html)  Modificar el estilo del contenedor  de `container-fluid
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-04.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-04.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-05.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-05.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-06.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-06.html)
Mismo comentario que los anteriores.

2020-08-27 00:25 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-07.html)
Mismo comentario que los anteriores.

2020-08-27 00:26 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-07.html)
Mismo comentario que los anteriores.

2020-08-27 00:54 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* Observar que se trata de cuidar que la suma de las columnas + los offsets sea 12.
@alexJava2015  Misma duda ... no me queda claro de donde sale ese "19". Sin embargo creo que faltó explicar como se comportan estos ejemplos, en especial para los renglones 3 y 4.  Agregaré detalle  para que se entienda.

2020-08-27 01:26 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo02/grid-example-07.html)
Mismo comentario respecto a las ligas

2020-08-27 01:26 UTC, jorgerdc commented on bootstrap/docs/modulo02.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo02/grid-example-07.html)
Mismo comentario respecto a las ligas

2020-08-27 01:26 UTC, jorgerdc commented on bootstrap/docs/modulo03.md
> +* El  código completo puede consultarse [aquí.](../ejemplos/modulo03/form-example-07.html)
Mismo comentario respecto a las ligas

2020-08-27 01:27 UTC, jorgerdc commented on bootstrap/docs/modulo03.md
> +* El resultado del ejemplo se puede visualizar [aquí.](https://jorgerdc.github.io/tutoriales/bootstrap/ejemplos/modulo03/form-example-07.html)
Mismo comentario respecto a las ligas

2020-08-27 15:31 UTC, vservin commented on bootstrap/docs/modulo02.md
> +* Observar que se trata de cuidar que la suma de las columnas + los offsets sea 12.
Exactamente en que linea están sumando 19? Probablemente te refieres a que por ejemplo puedo tener algo como ésto:
```html
<div class="row">
  <div class="col-sm-6 col-md-5 col-lg-6">.col-sm-6 .col-md-5 .col-lg-6</div>
  <div class="col-sm-6 col-md-5 offset-md-2 col-lg-6 offset-lg-0">
    .col-sm-6 .col-md-5 .offset-md-2 .col-lg-6 .offset-lg-0
  </div>
</div>
```
Pero realmente es válido porque usas breakpoints diferentes. La suma de "12" es para un breakpoint igual, del ejemplo anterior, si usamos una pantalla que entre en "lg", se ignoran los breakpoints mas pequeños, la suma de los "col-lg" es 6 + 6 + 0 (tamaño + tamaño + offset) = 12, para "md" 5 + 5 + 2 = 12, para sm 6 + 6 = 12.

Tomado de los ejemplos en [Bootstrap grid system](https://getbootstrap.com/docs/4.0/layout/grid/#offset-classes)

2020-09-01 18:31 UTC, jorgerdc commented
Estimados revisores, @alexJava2015  @vservin  @rhofp  No he recibido feedback del último commit de este PR. De favor, podrían invertir unos minutos y revisar si hay nuevos comentarios?  En su defecto, podrían cerrar las conversaciones que consideren resueltas y de ser el caso aprobar ?  Mil gracias !

2020-09-01 19:40 UTC, vservin approved these changes
Aprobado

2020-09-01 20:56 UTC, alexJava2015 approved these changes

2020-09-01 21:29 UTC, SamArtGS approved these changes

2020-09-01 23:22 UTC, merged