Se agrega un ejemplo sencillo para ilustrar la creación de Apps con ReactJS
jorgerdc/tutoriales pull request #49
Opened 2020-09-06 18:30 UTC by jorgerdc

En este ejemplo se agregan 2 componentes sencillos empleando ya la estructura de un proyecto ReactJS en forma.
Se actualiza `modulo09.md` para documentar el ejemplo.

2020-09-08 06:19 UTC, vservin requested changes

2020-09-08 06:19 UTC, vservin commented on reactjs/docs/modulo09/modulo09.md
> +* Como se mencionó anteriormente `npm`se emplea para  instalar paquetes o dependencias  así como para administrar sus versiones.  Existe una infinidad de librerías NodeJS que pueden ser empleadas en
Corregir `proyectoEn`

2020-09-08 06:19 UTC, vservin commented on reactjs/docs/modulo09/modulo09.md
> +  margin 16px;
Corregir a `margin: 16px;`

2020-09-08 06:19 UTC, vservin commented on reactjs/docs/modulo09/modulo09.md
> +* Inicializar el estado del componente `App` con un un atributo `texto`
Corregir `un un`

2020-09-12 17:57 UTC, alexJava2015 approved these changes, later dismissed

2020-09-17 01:04 UTC, jorgerdc commented on reactjs/docs/modulo09/modulo09.md
> +* Como se mencionó anteriormente `npm`se emplea para  instalar paquetes o dependencias  así como para administrar sus versiones.  Existe una infinidad de librerías NodeJS que pueden ser empleadas en
corregido.

2020-09-17 01:06 UTC, jorgerdc commented on reactjs/docs/modulo09/modulo09.md
> +* Inicializar el estado del componente `App` con un un atributo `texto`
corregido

2020-09-17 16:56 UTC, vservin approved these changes

2020-09-17 20:04 UTC, SamArtGS approved these changes

2020-09-19 01:14 UTC, merged