Dev vservin typescript
jorgerdc/tutoriales pull request #50
Opened 2020-09-08 05:57 UTC by vservin

- Se crea curso con ejemplo de reactjs de TypeScript

2020-09-11 01:33 UTC, alexJava2015 requested changes

2020-09-11 01:33 UTC, alexJava2015 commented on angular/docs/modulo01.md
> +1.5. [Angular Material](#angular-material)
Corregir la redacción, da el efecto que las palabras están al revés.

NOTA: Esto aplica para el texto de los diversos módulos.

2020-09-11 01:33 UTC, alexJava2015 commented on angular/docs/modulo01.md
> +## Introducción a Angular
Se sugiere agregar el número a todos los títulos según corresponda al temario, aunque se especifica arriba, en el contenido del módulo también debe llevarlo, esto con finalidad de evitar se olvide colocar la numeración correspondiente cuando desarrolle el mismo.

NOTA: Esta sugerencia aplica para todos los módulos: modulo01, modulo02, modulo03, modulo04, modulo05, modulo06, modulo07.

2020-09-11 01:51 UTC, vservin commented on angular/docs/modulo01.md
> +1.5. [Angular Material](#angular-material)
Si estás registrando la ultima versión del branch? si te das cuenta en el último commit ya no está la carpeta "angular"

2020-09-11 01:52 UTC, vservin commented on angular/docs/modulo01.md
> +## Introducción a Angular
Si estás registrando la ultima versión del branch? si te das cuenta en el último commit ya no está la carpeta "angular" y por eso dice Outdated el PR

2020-09-16 18:30 UTC, jorgerdc commented
Hola @vservin Es un tanto complicado revisar un PR por primera vez con tal cantidad de commits.
Uno de los lineamientos para evitar esto es hacer una operación de rebase que en resumen realiza un merge de todos tus commits.  La explicación de esta convención la documenté [aquí](https://github.com/jorgerdc/tutoriales/blob/master/lineamientos-desarrollo/github/github-guidelines.md#18-pull-request-y-merge).
De preferencia,  cada PR no debe ser tan largo para que la revisión sea más precisa.
Recomiendo seguir estos lineamientos y volver a  registrar el PR.  Si es demasiado contenido, puedes hacer varios PRs.  :)

2020-09-17 01:17 UTC, vservin commented
De acuerdo @jorgerdc le echaré un ojo al rebase, ando acostumbrado a hacer muchos commits pequeños, gracias!

2020-09-17 01:44 UTC, jorgerdc commented
Si, de hecho hacer commits pequeños es lo mejor. Pero el PR inicial debería ser uno solo. Por otro lado, el PR inicial también debería incluir pocos archivos para que la primera revisión no sea tan larga.
Si pudieras hacer eso, estaría genial... 
Espero haberme dado a entender 👍

2020-09-17 17:16 UTC, closed without merging