Se agregan ligas en los archivos md para mostrar el código y el render de los ejemplos.
jorgerdc/tutoriales pull request #51
Opened 2020-09-09 04:43 UTC by jorgerdc

Nota: La segunda liga que apunta al html para visualizar el resultado del ejemplo la cual apunta a https://jorgerdc.github.io/tutoriales  no funcionará hasta que se haga merge debido a que esta URL apunta al sitio
del repo https://jorgerdc.github.io/tutoriales.
Dicho sitio se actualiza con base al contenido de la rama master. Por lo tanto,  mientras no se haga merge a master, esta liga no funcionará, no es un error. Solo se sugiere revisar que la ruta posterior a https://jorgerdc.github.io/tutoriales  apunte al archivo correcto.

2020-09-10 21:24 UTC, vservin requested changes

2020-09-10 21:24 UTC, vservin commented on reactjs/docs/modulo05.md
> +* En general el concepto de Rendering condicional se refiere a la posibilidad de in### 5.1. Render de ciertos cormporar sentencias de control  javascript, como son  `if`, `else`, operador `?` , `:`,
Me parece que aquí fallo algo al poner `### 5.1. Render de ciertos `, corregir

2020-09-16 20:10 UTC, jorgerdc commented on reactjs/docs/modulo05.md
> +* En general el concepto de Rendering condicional se refiere a la posibilidad de in### 5.1. Render de ciertos cormporar sentencias de control  javascript, como son  `if`, `else`, operador `?` , `:`,
Algo pasó con el editor, se copió y pegó un texto incorrecto. Ya fue corregido. Mil gracias.

2020-09-17 16:55 UTC, vservin approved these changes

2020-09-17 16:56 UTC, merged