Add new section for "git head" unifications of commits
jorgerdc/tutoriales pull request #8
Opened 2019-03-18 23:28 UTC by alexJava2015

2019-03-24 06:13 UTC, jorgerdc requested changes
Listo. Porfa, revisar comentarios y corregir.

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +#### 1.8.1 Unificar commits Antes De Generar Pull Request
cambiar:  
Antes -> antes
Generar -> generar

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> + Cuando se necesita unificar N commits, es necesario ejecutar ciertos comandos, esto tiene la finalidad de ayudar al revisor a simplificar la lectura y dar observaciones correspondientes, además de s
Creo que aquí hace falta un par de enunciados para explicar la necesidad de unificar. Algo así:
- Durante el proceso de desarrollo de una tarea asociada a un branch, es posible realizar varias operaciones `commit` e inclusive operaciones `push` hacia el Fork. 
- Una vez que la tarea está lista para ser revisada, se deberá solicitar un "Pull Request" como se mencionó anteriormente. 
- Al existir varias operaciones `commit`, el  Pull Request incluirá la lista de todos los commits realizados por el programador. 
- Los revisores tendrán que revisar cada uno de estos commits lo cual puede ser tedioso o inclusive confuso.  Lo ideal sería tener un solo commit ya que se trata de la primera revisión.
- Git permite realizar una *unificación*  de esta lista de commits  de tal forma que el revisor verá uno solo y por lo tanto facilitará su revisión.
- Lo anterior permite establecer la siguiente regla: Todos los programadores deberán unificar sus commits antes de crear un Pull Request.
- Git hace uso del siguiente comando para realizar  la unificación de commits:
CONTINUAR AQUÍ CON TU EXPLICACIÓN EN LA LÍNEA 170

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +El comando anterior mostrará un wizard a nivel consola en el cual se deben especificar ciertos paramatros necesarios para la tarea.
ciertos parametros necesarios para la tarea ->
ciertos parámetros requeridos para realizar la unificación de commits.

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +La siguiente sección muestra el primer paso de la configuración donde se puede observar un ménu con los históricos de los comentarios realizados y las posibles opciones a aplicar. Para efecto de este
La siguiente sección -> En el siguiente ejemplo, se muestra...

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +Nota: Para aplicar el cambio previamente  descrito se debe borrar la palabra "pick" y teclear la letra "s".
No me quedó clara esta instrucción.  ¿ en qué parte se borra la palabra Pick ? en el ejemplo, las lineas 177 a 181 comienzan con Pick. ¿en cuál de estas líneas se hace el cambio ?  Abajo ya muestras como debe quedar, pero creo que debes indicar aquí qué linea debes editar.

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +Observar como el primer elemento de la lista debe de ser inmutable ya que es el Hash principal con el que se hará la unificación de comentarios, por lo cual debe quedar intacto.
Podrías explicar con palabras mas sencillas la oración de la lìnea 189? no se entiende del todo al decir "inmutable ya que es el hash principal"... esta partecita no se entiende.. me quede de "what..."

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +pick a5f4a0d added cat-file
Por lo que entiendo, todos los renglones que inician con pick, representan un commit diferente. Si esto es cierto, creo que sería bueno agregar una viñeta que diga que cada renglón es un commit.  
Por otro lado, supongo que lo que sigue después del numero del commit (creo que se le llama hash cierto?) se refiere al mensaje o descripción del commit. De ser así, creo que sería mas didáctico quitar esas descripciones y poner descripción del commit 1, etc... algo asi:
```bash 
+pick f7f3f6d descripción commit 1
+pick 310154e descripción commit 2
+pick a5f4a0d descripción commit 3
+pick 310154e descripción commit 4
```

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +*Guardar cambios correspondientes, esto será en funcion del editor configurado en el equipo.
Please, corregir la viñeta.  +* -> * Guardar.
Por otro lado, ¿podrías revisar si en el documento se explica como configurar el editor ? En caso de no existir, agrega una sección para configurarlo. No tiene que ser en esta sección.

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +Posterior a esto se mostrará la segunda pantalla del wizard en el que se deberá especificar los comentarios que queremos conservar para  la revisión.
corregir viñeta línea 205

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +*Guardar cambios correspondientes, esto será en funcion del editor configurado en el equipo. Se recomienda ejecutar `git log` para estar seguros de lo realizado anteriormente.
corregir viñeta en la lìnea 215

2019-03-24 06:13 UTC, jorgerdc commented on lineamientos-desarrollo/github/github-guidelines.md
> +#### Creación De Pull Request En Git Hub
Aquí faltó poner el número de sección: 1.8.2

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +#### 1.8.1 Unificar commits Antes De Generar Pull Request
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> + Cuando se necesita unificar N commits, es necesario ejecutar ciertos comandos, esto tiene la finalidad de ayudar al revisor a simplificar la lectura y dar observaciones correspondientes, además de s
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +El comando anterior mostrará un wizard a nivel consola en el cual se deben especificar ciertos paramatros necesarios para la tarea.
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +La siguiente sección muestra el primer paso de la configuración donde se puede observar un ménu con los históricos de los comentarios realizados y las posibles opciones a aplicar. Para efecto de este
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +pick a5f4a0d added cat-file
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +Nota: Para aplicar el cambio previamente  descrito se debe borrar la palabra "pick" y teclear la letra "s".
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +Observar como el primer elemento de la lista debe de ser inmutable ya que es el Hash principal con el que se hará la unificación de comentarios, por lo cual debe quedar intacto.
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +*Guardar cambios correspondientes, esto será en funcion del editor configurado en el equipo.
En revisión.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +Posterior a esto se mostrará la segunda pantalla del wizard en el que se deberá especificar los comentarios que queremos conservar para  la revisión.
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +*Guardar cambios correspondientes, esto será en funcion del editor configurado en el equipo. Se recomienda ejecutar `git log` para estar seguros de lo realizado anteriormente.
Se genero el cambio solicitado, favor de revisar.

2019-03-25 02:11 UTC, alexJava2015 commented on lineamientos-desarrollo/github/github-guidelines.md
> +#### Creación De Pull Request En Git Hub
Se genero el cambio solicitado, favor de revisar.

2019-04-20 22:40 UTC, closed without merging