Add README
jorgerdc/tutoriales pull request #9
Opened 2019-03-24 04:42 UTC by jorgerdc

Adding README to lineamientos-programacion.
Please @alexJava2015  review.

2019-03-24 20:56 UTC, alexJava2015 requested changes

2019-03-24 20:56 UTC, alexJava2015 commented on lineamientos-desarrollo/README.md
> +* En la subcarpeta `github` se encuentra un documento llamado `ithub-guidelines.md` En el se definen los lineamientos y buenas prácticas  que deberán aplicarse para contribuir  con los proyectos inde
Falta de ortografía, falta la letra "g" al inicio del texto "ithub-guidelines.md"

2019-04-03 00:22 UTC, jorgerdc commented on lineamientos-desarrollo/README.md
> +* En la subcarpeta `github` se encuentra un documento llamado `ithub-guidelines.md` En el se definen los lineamientos y buenas prácticas  que deberán aplicarse para contribuir  con los proyectos inde
Corregido.  Ya agregué  a trello la tarea para agregar una sección que explique el uso de gradle.

2019-04-04 05:05 UTC, alexJava2015 approved these changes

2019-04-05 21:57 UTC, merged